// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:25b72563-6b90-47c9-9ae2-2527791bb28d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JgX4lcZId",
    "aws_user_pools_web_client_id": "7q1bmknsv8ggmaeadv0drft55g"
};


export default awsmobile;
